language: rust
rust:
  - nightly
  - beta
  - 1.31.0 # stable

addons:
  apt:
    packages:
    - libgtk-3-dev
    - libgtksourceview-3.0-dev
script:
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
    make regen_check;
    fi
  - cargo build
  - cargo build --features "v3_10 futures"
