[options]
girs_dir = "gir-files"
library = "GtkSource"
version = "3.0"
min_cfg_version = "3.0"
target_path = "."
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
    "GtkSource.BackgroundPatternType",
    "GtkSource.ChangeCaseType",
    "GtkSource.CompletionActivation",
    "GtkSource.CompletionProposal",
    "GtkSource.CompletionProvider",
    "GtkSource.CompressionType",
    "GtkSource.DrawSpacesFlags",
    "GtkSource.Encoding",
    "GtkSource.FileSaverFlags",
    "GtkSource.GutterRendererAlignmentMode",
    "GtkSource.GutterRendererState",
    "GtkSource.Language",
    "GtkSource.MountOperationFactory",
    "GtkSource.NewlineType",
    "GtkSource.SmartHomeEndType",
    "GtkSource.SortFlags",
    "GtkSource.SpaceLocationFlags",
    "GtkSource.SpaceTypeFlags",
    "GtkSource.StyleSchemeChooser",
    "GtkSource.UndoManager",
    "GtkSource.ViewGutterPosition",
]

ignore = [
]

manual = [
    "cairo.Context",
    "Gdk.Event",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "Gdk.Window",
    "GdkPixbuf.Pixbuf",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.Icon",
    "Gio.InputStream",
    "Gio.Settings",
    "Gio.SettingsBindFlags",
    "GLib.Error",
    "GLib.Priority",
    "GLib.Variant",
    "Gtk.Actionable",
    "Gtk.Adjustment",
    "Gtk.Bin",
    "Gtk.Buildable",
    "Gtk.Button",
    "Gtk.Container",
    "Gtk.PrintContext",
    "Gtk.Scrollable",
    "Gtk.ScrollablePolicy",
    "Gtk.ScrollStep",
    "Gtk.TextBuffer",
    "Gtk.TextIter",
    "Gtk.TextMark",
    "Gtk.TextTag",
    "Gtk.TextTagTable",
    "Gtk.TextView",
    "Gtk.TextWindowType",
    "Gtk.Tooltip",
    "Gtk.Unit",
    "Gtk.Widget",
    "Gtk.Window",
    "Gtk.WrapMode",
    "GtkSource.RegionIter",
    "Pango.FontDescription",
    "Pango.Underline",
]

[[object]]
name = "GtkSource.Buffer"
status = "generate"
generate_builder = true
    [[object.function]]
    name = "set_undo_manager"
    version = "2.10"
    [[object.function]]
    name = "get_undo_manager"
    version = "2.10"

[[object]]
name = "GtkSource.Completion"
status = "generate"
generate_builder = true
    [[object.function]]
    name = "create_context"
    ignore = true

[[object]]
name = "GtkSource.CompletionContext"
status = "generate"
generate_builder = true
    [[object.property]]
    name = "iter"
    ignore = true

[[object]]
name = "GtkSource.CompletionInfo"
status = "generate"
    [[object.function]]
    name = "move_to_iter"
    ignore = true

[[object]]
name = "GtkSource.CompletionItem"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.CompletionWords"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.File"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.FileLoader"
status = "generate"
generate_builder = true
manual_traits = ["FileLoaderExtManual"]
    [[object.function]]
    name = "set_candidate_encodings"
    #array of boxed to GSList
    ignore = true
    [[object.function]]
    name = "load_async"
    #callbacks and async parameters at the same time
    ignore = true
    doc_trait_name = "FileLoaderExtManual"

[[object]]
name = "GtkSource.FileSaver"
status = "generate"
generate_builder = true
manual_traits = ["FileSaverExtManual"]
    [[object.function]]
    name = "save_async"
    #callbacks and async parameters at the same time
    ignore = true
    doc_trait_name = "FileSaverExtManual"

[[object]]
name = "GtkSource.Gutter"
status = "generate"
generate_builder = true
    [[object.function]]
    name = "get_padding"
    ignore = true

[[object]]
name = "GtkSource.GutterRenderer"
status = "generate"
    [[object.function]]
    name = "begin"
        [[object.function.parameter]]
        name = "cr"
        const = true
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
        name = "cr"
        const = true

[[object]]
name = "GtkSource.GutterRendererPixbuf"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.GutterRendererText"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.LanguageManager"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.Map"
status = "generate"
generate_builder = true
    [[object.property]]
    name = "font-desc"
    ignore = true

[[object]]
name = "GtkSource.Mark"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.MarkAttributes"
status = "generate"
generate_builder = true
version = "2.2"
    [[object.function]]
    name = "get_pixbuf"
    ignore = true
    [[object.function]]
    name = "render_icon"
    ignore = true
    [[object.property]]
    pattern = ".+"
    version = "2.2"

[[object]]
name = "GtkSource.PrintCompositor"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.Region"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.SearchContext"
status = "generate"
generate_builder = true
    [[object.function]]
    name = "replace_all"
        [object.function.return]
        use_return_for_result = true

[[object]]
name = "GtkSource.SearchSettings"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.SpaceDrawer"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.Style"
status = "generate"
version = "2.0"
generate_builder = true
    [[object.function]]
    name = "copy"
    ignore = true
    [[object.function]]
    name = "apply"
    ignore = true

[[object]]
name = "GtkSource.StyleScheme"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.StyleSchemeChooserButton"
status = "generate"
version = "3.16"

[[object]]
name = "GtkSource.StyleSchemeChooserWidget"
status = "generate"
version = "3.16"

[[object]]
name = "GtkSource.StyleSchemeManager"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.Tag"
status = "generate"
generate_builder = true

[[object]]
name = "GtkSource.View"
status = "generate"
    [[object.function]]
    name = "get_mark_attributes"
    ignore = true
    [[object.function]]
    name = "set_mark_attributes"
    version = "2.2"
